Fixing database url #3

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -41,8 +41,15 @@ jobs:
       - name: Set DATABASE_URL
         run: echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/TodoApplicationDatabase_test" >> $GITHUB_ENV
 
-      - name: Print DATABASE_URL
-        run: echo "✅ DATABASE_URL is set to: $DATABASE_URL"
+      - name: Verify DATABASE_URL
+        run: |
+          if [ -z "$DATABASE_URL" ]; then
+            echo "::error::❌ DATABASE_URL is NOT set"
+            exit 1
+          else
+            echo "✅ DATABASE_URL is set"
+          fi
+
 
 
 
