Debugging db url output

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -54,15 +54,15 @@ jobs:
         #   ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
 
 
-      # - name: Verify DATABASE_URL
-      #   run: |
-      #     echo "DATABASE_URL is: $DATABASE_URL"
-      #     if [ -z "$DATABASE_URL" ]; then
-      #       echo "::error::❌ DATABASE_URL is NOT set"
-      #       exit 1
-      #     else
-      #       echo "✅ DATABASE_URL is set"
-      #     fi
+      - name: Verify DATABASE_URL
+        run: |
+          echo "DATABASE_URL is: $DATABASE_URL"
+          if [ -z "$DATABASE_URL" ]; then
+            echo "::error::❌ DATABASE_URL is NOT set"
+            exit 1
+          else
+            echo "✅ DATABASE_URL is set"
+          fi
 
 
 
